/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Marko
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
        setIcon();
    }
    
    public void getIssuedBookDetails(){
        
        
        int bookId = Integer.parseInt(txt_bookId.getText());
        int userId = Integer.parseInt(txt_userId.getText());
        
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "select * from issue_book_details where book_id = ? and user_id = ? and status = ?";
            PreparedStatement prepareStatement = connection.prepareStatement(sql);
            prepareStatement.setInt(1, bookId);
            prepareStatement.setInt(2, userId);
            prepareStatement.setString(3, "Posuđena");
            
            ResultSet resultSet = prepareStatement.executeQuery();
            if(resultSet.next()){
                
                lbl_issueId.setText(resultSet.getString("id"));
                lbl_bookName.setText(resultSet.getString("book_name"));
                lbl_userName.setText(resultSet.getString("user_name"));
                lbl_issueDate.setText(resultSet.getString("issue_date"));
                lbl_dueDate.setText(resultSet.getString("due_date"));
                lbl_bookError.setText("");
            }else{
                lbl_bookError.setText("Zapis nije pronađen.");
                
                lbl_issueId.setText("");
                lbl_bookName.setText("");
                lbl_userName.setText("");
                lbl_issueDate.setText("");
                lbl_dueDate.setText("");
                
            }
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    public boolean returnBook(){
        
        boolean isReturned = false;
        int bookId = Integer.parseInt(txt_bookId.getText());
        int userId = Integer.parseInt(txt_userId.getText());
        
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "update issue_book_details set status = ? where user_id = ? and book_id = ? and status = ?";
            PreparedStatement prepareStatement = connection.prepareStatement(sql);
            
            prepareStatement.setString(1, "Vraćena");
            prepareStatement.setInt(2, userId);
            prepareStatement.setInt(3, bookId);
            prepareStatement.setString(4, "posuđena");
            
            int rowCount = prepareStatement.executeUpdate();
            if(rowCount > 0){
                isReturned = true;
            }else{
                isReturned = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isReturned;
    }
    
    public void updateBookCount(){
        int bookId = Integer.parseInt(txt_bookId.getText());
        try {
            Connection connection = DBConnection.getConnection();
            String sql = "update book_details set quantity = quantity + 1 where book_id = ?";
            PreparedStatement prepareStatement = connection.prepareStatement(sql);
            prepareStatement.setInt(1, bookId);
            
            int rowCount = prepareStatement.executeUpdate();
            if(rowCount > 0){
                JOptionPane.showMessageDialog(this, "Broj knjiga ažuriran.");
            }else{
                JOptionPane.showMessageDialog(this, "Broj knjiga nije ažuriran.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_bookId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_userId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        issueBookButton = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_issueId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        lbl_bookError = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_dueDate = new javax.swing.JLabel();
        issueBookButton1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Marko\\Faks\\5. Godina\\Diplomski rad\\Icons\\issue_book_icon.png")); // NOI18N
        jLabel2.setText("Vrati knjigu");
        panelMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        txt_bookId.setBackground(new java.awt.Color(51, 51, 51));
        txt_bookId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        panelMain.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 440, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ID knjige");
        panelMain.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        txt_userId.setBackground(new java.awt.Color(51, 51, 51));
        txt_userId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_userId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userIdFocusLost(evt);
            }
        });
        txt_userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userIdActionPerformed(evt);
            }
        });
        panelMain.add(txt_userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 440, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("ID korisnika");
        panelMain.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        issueBookButton.setBackground(new java.awt.Color(0, 0, 51));
        issueBookButton.setText("Pretraživanje knjiga");
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });
        panelMain.add(issueBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 430, 80));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Marko\\Faks\\5. Godina\\Diplomski rad\\Icons\\back_icon.png")); // NOI18N
        jLabel18.setText("Povratak");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Marko\\Faks\\5. Godina\\Diplomski rad\\Icons\\issued_books_icon.png")); // NOI18N
        jLabel19.setText("Podatci o knjizi");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Datum posudbe");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        lbl_issueDate.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 230, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Ime knjige");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Ime korisnika");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("ID posudbe");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_issueId.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_issueId.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 30));

        lbl_bookName.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 230, 30));

        lbl_userName.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 230, 30));

        lbl_bookError.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lbl_bookError.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 390, 40));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Rok posudbe");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 30));

        lbl_dueDate.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_dueDate.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 230, 30));

        panelMain.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 650));

        issueBookButton1.setBackground(new java.awt.Color(51, 0, 51));
        issueBookButton1.setText("Vrati knjigu");
        issueBookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButton1ActionPerformed(evt);
            }
        });
        panelMain.add(issueBookButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 430, 80));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 650));

        setSize(new java.awt.Dimension(953, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdFocusLost

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void txt_userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userIdActionPerformed

    private void txt_userIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userIdFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_userIdFocusLost

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        // TODO add your handling code here:
        
        getIssuedBookDetails();
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void issueBookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButton1ActionPerformed
        // TODO add your handling code here:
        if(returnBook() == true){
            JOptionPane.showMessageDialog(this, "Knjiga vraćena.");
            updateBookCount();
        }else{
            JOptionPane.showMessageDialog(this, "Knjiga nije vraćena.");
        }
    }//GEN-LAST:event_issueBookButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatDarkLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle issueBookButton;
    private rojerusan.RSMaterialButtonCircle issueBookButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_bookError;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dueDate;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_issueId;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txt_bookId;
    private javax.swing.JTextField txt_userId;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("app-icon.png")));
    }
}
